name: StormCast
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - aioboto3
  - boto3
  - cfgrib
  - numpy
  - netcdf4
  - scikit-image
  - scipy
  - shapely
  - rasterio
  - xarray
  - folium
  - psutil
  - tensorflow
  - pytorch
  - pip:
    - gputil
